apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: scp
  name: scp-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: scp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scp-service
                port:
                  number: 80
