package com.example.scp;

import com.example.scp.entity.BonBon;
import com.example.scp.repository.BonBonRepository;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.system.CapturedOutput;
import org.springframework.boot.test.system.OutputCaptureExtension;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.HttpStatus;
import org.springframework.test.context.jdbc.Sql;

import java.net.URI;
import java.util.List;

@ExtendWith(OutputCaptureExtension.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class ApplicationTests {
    private static final Logger LOGGER = LoggerFactory.getLogger(ApplicationTests.class);

    @Autowired
    private TestRestTemplate testRestTemplate;
    @Autowired
    private BonBonRepository bonBonRepository;

    @BeforeAll
    public static void beforeAll() {
        LOGGER.info("JUnit5@BeforeAll is called");
    }

    @AfterAll
    public static void afterAll() {
        LOGGER.info("JUnit5@AfterAll is called");
    }

    @BeforeEach
    public void beforeEach() {
        LOGGER.info("JUnit5@BeforeEach is called");
    }

    @AfterEach
    public void afterEach() {
        LOGGER.info("JUnit5@AfterEach is called");
    }

    @Test
    @Sql(statements = {
            "create table if not exists bon_bon (id bigint generated by default as identity, candy_type varchar(255), primary key (id))",
            "insert into bon_bon(candy_type) values ('tasty')"
    })
    void testOne(CapturedOutput output) {
        var response = testRestTemplate.getForEntity(
                URI.create("/"),
                Void.class
        );
        Assertions.assertEquals(HttpStatus.OK.value(), response.getStatusCode().value());
        List<BonBon> all = bonBonRepository.findAll();
        Assertions.assertFalse(all.isEmpty());
    }

    @Test
    @Sql(statements = {
            "create table if not exists bon_bon (id bigint generated by default as identity, candy_type varchar(255), primary key (id))",
            "insert into bon_bon(candy_type) values ('tasty')"
    })
    void testTwo(CapturedOutput output) {
        var response = testRestTemplate.getForEntity(
                URI.create("/"),
                Void.class
        );
        Assertions.assertEquals(HttpStatus.OK.value(), response.getStatusCode().value());
        List<BonBon> all = bonBonRepository.findAll();
        Assertions.assertFalse(all.isEmpty());
    }

}
