package com.example.scp;

import com.example.scp.entity.BonBon;
import com.example.scp.repository.BonBonRepository;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.system.OutputCaptureExtension;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.jdbc.Sql;

import java.net.URI;
import java.util.List;
import java.util.Map;

@ExtendWith(OutputCaptureExtension.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class SqlTests {
    private static final Logger LOGGER = LoggerFactory.getLogger(SqlTests.class);

    @Autowired
    private TestRestTemplate testRestTemplate;
    @Autowired
    private JdbcTemplate jdbcTemplate;
    @Autowired
    private BonBonRepository bonBonRepository;

    @Test
    @Sql(statements = {
            "create table if not exists bon_bon (id bigint generated by default as identity, candy_type varchar(255), primary key (id))",
            "insert into bon_bon(candy_type) values ('tasty')"
    })
    void testOne() {
        LOGGER.info("SqlTests is called. testOne");
        List<BonBon> all = bonBonRepository.findAll();
        Assertions.assertFalse(all.isEmpty());
    }

    @Test
    @Sql(statements = {
            "create table if not exists bon_bon (id bigint generated by default as identity, candy_type varchar(255), primary key (id))",
            "insert into bon_bon(candy_type) values ('tasty')"
    })
    void testTwo() {
        LOGGER.info("SqlTests is called. testTwo");
        var response = testRestTemplate.getForEntity(
                URI.create("/"),
                Void.class
        );
        Assertions.assertEquals(HttpStatus.OK.value(), response.getStatusCode().value());
        List<BonBon> all = bonBonRepository.findAll();
        Assertions.assertFalse(all.isEmpty());
        List<Map<String, Object>> maps = jdbcTemplate.queryForList(
                "select * from bon_bon"
        );
        Assertions.assertEquals("tasty", maps.get(0).get("candy_type"));
    }

}
